#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     handMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Include header file
#include "CGHSOpenHouse.h"

task main()
{
	preInit();
	waitForStart();
	postInit();
	while (running)
	{
		getJoystickSettings(joystick);
		twoJoystickControls();
		checkButtons();
		updateDisplay();
	}
}

void preInit()
{
	disableDiagnosticsDisplay();
	eraseDisplay();
	setRunning(true);
	setDeadZone(15);
	setAmountOfButtonsUsed(10);
	nxtDisplayTextLine(0, "===[CGHS]===");
	nxtDisplayTextLine(1, "Awaiting orders");
	nxtDisplayTextLine(2, "from command");
}

void postInit()
{
	eraseDisplay();
}

void updateDisplay()
{
	nxtDisplayTextLine(0, "===[CGHS]===");
	nxtDisplayTextLine(1, "Status: Running");
}

bool onController1Button1(bool isPressed)
{
	if (isPressed)
	{
		setMotorSpeed(handMotor, currentPower);
		btn1Controller1BeingPressed = true;
	}
	else
	{
		btn1Controller1BeingPressed = false;
	}
	return isPressed;
}

bool onController1Button2(bool isPressed)
{
	if (isPressed)
	{
		setMotorSpeed(handMotor, -(currentPower));
		btn2Controller1BeingPressed = true;
	}
	else
	{
		btn2Controller1BeingPressed = false;
	}
	return isPressed;
}

bool onController1Button3(bool isPressed)
{
	if (isPressed)
	{
		btn3Controller1BeingPressed = true;
	}
	else
	{
		btn3Controller1BeingPressed = false;
	}
	return isPressed;
}

bool onController1Button4(bool isPressed)
{
	if (isPressed)
	{
		btn4Controller1BeingPressed = true;
	}
	else
	{
		btn4Controller1BeingPressed = false;
	}
	return isPressed;
}


bool onController1Button5(bool isPressed)
{
	return isPressed;
}

bool onController1Button6(bool isPressed)
{
	return isPressed;
}

bool onController1Button7(bool isPressed)
{
	return isPressed;
}

bool onController1Button8(bool isPressed)
{
	return isPressed;
}

bool onController1Button10(bool isPressed)
{
	if (!isSoundActive && isPressed)
	{
		PlaySound(soundBeepBeep);
		btn10Controller1BeingPressed = true;
		currentPower = currentPower + 25;
		if (currentPower > 100)
		{
			currentPower = 25;
		}
	}
	else if (isPressed)
	{
		btn10Controller1BeingPressed = true;
	}
	else
	{
		btn10Controller1BeingPressed = false;
	}
	return isPressed;
}

bool onController1Button4(bool isPressed)
{
	if (isPressed)
	{		btn4Controller1BeingPressed = true;
	}
	else
	{
		btn4Controller1BeingPressed = false;
	}
	return isPressed;
}

bool onController2Button1(bool isPressed)
{
	return isPressed;
}

bool onController2Button2(bool isPressed)
{
	return isPressed;
}

void onNothingBeingPressed()
{
	if (!btn2Controller1BeingPressed && !btn4Controller1BeingPressed)
	{
		setMotorSpeed(handMotor, 0);
	}
}
